variable "aws_region" {}
variable "destination_cidr_block" {}
variable "vpc_id" {}
variable "vpc_tg" {}
variable "igw_tg" {}
variable "pub_sub_1a_tg" {}
variable "pub_sub_1b_tg" {}
variable "pub_sub_1c_tg" {}
variable "pub_rtb_tg" {}
variable "acls_pub_prod_tg" {}
variable "demo_env_default_tags" {}