variable "region" {}
variable "destination_cidr_block" {}
variable "vpc_id" {}
variable "vpc_tg" {}
variable "igw_tg" {}
variable "public_tg" {}
variable "public_rtb_tg" {}
variable "acls_public_prod_tg" {}
variable "demo_env_default_tags" {}